# dotnet code build

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/heads/NCSD-306_grunt_yamltemplate
    endpoint: 'GitHub (CDH)'

variables:
  npmroot: 'src'
  assetpath: 'assets/dist' # subfolder off npmfolder

trigger:
  batch: true # batch if multiple checkins while build in progress
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master

jobs:

# Full build
- job: BuildDotNetCore
  displayName: Build dot net core project
  pool:
    name: Continuous Integration 02 - SSD - 160ACU
    demands:
    - npm
    - grunt

  steps:

  # Resources
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Resources'
    inputs:
      pathtoPublish: 'Resources'
      artifactName: resources

  # build and publish gds_toolkit
  - template: AzureDevOpsTemplates/Build/dfc-grunt-build.yml@dfc-devops
    parameters:
      npmfolder: '$(npmroot)/gds_toolkit'
      publishpath: '$(assetpath)'
      publishname: 'gds_toolkit'

  # build and publish gds_service_toolkit
  - template: AzureDevOpsTemplates/Build/dfc-grunt-build.yml@dfc-devops
    parameters:
      npmfolder: '$(npmroot)/gds_service_toolkit'
      publishpath: '$(assetpath)'
      publishname: 'gds_service_toolkit'
