//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitefinityWebApp.ResourcePackages.GdsSfa.client_components.fields.text_field {
    
    
    public partial class CustomTextField {
        
        /// <summary>
        /// conditionalTemplate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Sitefinity.Web.UI.ConditionalTemplateContainer conditionalTemplate;
        
        /// <summary>
        /// titleLabel_read control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Sitefinity.Web.UI.SitefinityLabel titleLabel_read;
        
        /// <summary>
        /// tooltip_read control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Sitefinity.Web.UI.SitefinityToolTip tooltip_read;
        
        /// <summary>
        /// textLabel_read control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Sitefinity.Web.UI.SitefinityLabel textLabel_read;
        
        /// <summary>
        /// descriptionLabel_read control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Sitefinity.Web.UI.SitefinityLabel descriptionLabel_read;
        
        /// <summary>
        /// characterCounter_read control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Sitefinity.Web.UI.SitefinityLabel characterCounter_read;
        
        /// <summary>
        /// titleLabel_write control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label titleLabel_write;
        
        /// <summary>
        /// tooltip_write control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Sitefinity.Web.UI.SitefinityToolTip tooltip_write;
        
        /// <summary>
        /// expandButton_write control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton expandButton_write;
        
        /// <summary>
        /// expandableTarget_write control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel expandableTarget_write;
        
        /// <summary>
        /// textBox_write control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textBox_write;
        
        /// <summary>
        /// characterCounter_write control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Sitefinity.Web.UI.SitefinityLabel characterCounter_write;
        
        /// <summary>
        /// descriptionLabel_write control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Sitefinity.Web.UI.SitefinityLabel descriptionLabel_write;
        
        /// <summary>
        /// exampleLabel_write control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Sitefinity.Web.UI.SitefinityLabel exampleLabel_write;
        
        /// <summary>
        /// characterCounterDescription_write control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Sitefinity.Web.UI.SitefinityLabel characterCounterDescription_write;
    }
}
