# dotnet code build

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.9.1
    endpoint: 'GitHub (ESFA)'

variables:
  npmroot: 'src'
  assetpath: 'assets/dist' # subfolder off npmfolder

trigger:
  batch: true # batch if multiple checkins while build in progress
  branches:
    include:
    - master
    - release
    - hotfix

pr:
  branches:
    include:
    - master
    - release
    - hotfix

jobs:

# Full build
- job: BuildDotNetCore
  displayName: Build dot net core project
  pool:
    name: NCS - CI and CD
    demands:
    - npm

  steps:

  # Resources
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: ARM Templates'
    inputs:
      pathtoPublish: 'Resources/ArmTemplates'
      artifactName: resources
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: PowerShell scripts'
    inputs:
      pathtoPublish: 'Resources/PSScripts'
      artifactName: resources

  # build and publish gds_toolkit
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-grunt-build.yml@dfc-devops
    parameters:
      displayPrefix: 'gds_toolkit:'
      npmfolder: '$(npmroot)/gds_toolkit'
      publishpath: '$(assetpath)'
      publishname: 'gds_toolkit'

  # build and publish gds_service_toolkit
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-grunt-build.yml@dfc-devops
    parameters:
      displayPrefix: 'gds_service_toolkit:'
      npmfolder: '$(npmroot)/gds_service_toolkit'
      publishpath: '$(assetpath)'
      publishname: 'gds_service_toolkit'

  # build and publish gds_service_toolkit_BAU
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-grunt-build.yml@dfc-devops
    parameters:
      displayPrefix: 'gds_service_toolkit_BAU:'
      npmfolder: '$(npmroot)/gds_service_toolkit_BAU'
      publishpath: '$(assetpath)'
      publishname: 'gds_service_toolkit_BAU'      

  # build and publish nationalcareers_toolkit
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-grunt-build.yml@dfc-devops
    parameters:
      displayPrefix: 'nationalcareers_toolkit:'
      npmfolder: '$(npmroot)/nationalcareers_toolkit'
      publishpath: '$(assetpath)'
      publishname: 'nationalcareers_toolkit'      
